web:
  build: .
  command: 'bash -c ''websocket-chat-heroku'''
  working_dir: /app/user/src/github.com/Studia-AMW/websocket-chat-heroku
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
shell:
  build: .
  command: bash
  working_dir: /app/user/src/github.com/Studia-AMW/websocket-chat-heroku
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
  volumes:
    - '.:/app/user/src/github.com/Studia-AMW/websocket-chat-heroku'
herokuRedis:
  image: redis
